---
clusterName: elasticsearch
image: us-central1-docker.pkg.dev/planet-4-151612/elasticsearch/elasticsearch
imageTag: 9.1.2
# https://www.elastic.co/guide/en/elasticsearch/reference/7.8/cluster-health.html#request-params_wait_for_status
clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

maxUnavailable: 0

#kubectl create secret generic gcp-backup-key --from-file=gcs.client.default.credentials_file=./credentials.json -n elastic
